// Mock data for development — replace with API-Football calls in production

export const WC_LEAGUE_ID = 1
export const WC_SEASON = 2026

// ─── Teams ────────────────────────────────────────────────────────────────────

export const TEAMS = {
  ARG: { id: 'ARG', name: 'الأرجنتين',   flag: '🇦🇷', color: '#74ACDF' },
  FRA: { id: 'FRA', name: 'فرنسا',       flag: '🇫🇷', color: '#002395' },
  BRA: { id: 'BRA', name: 'البرازيل',    flag: '🇧🇷', color: '#009C3B' },
  ESP: { id: 'ESP', name: 'إسبانيا',     flag: '🇪🇸', color: '#AA151B' },
  GER: { id: 'GER', name: 'ألمانيا',     flag: '🇩🇪', color: '#000000' },
  ENG: { id: 'ENG', name: 'إنجلترا',     flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', color: '#FFFFFF' },
  POR: { id: 'POR', name: 'البرتغال',    flag: '🇵🇹', color: '#006600' },
  NED: { id: 'NED', name: 'هولندا',      flag: '🇳🇱', color: '#FF4F00' },
  MAR: { id: 'MAR', name: 'المغرب',      flag: '🇲🇦', color: '#C1272D' },
  BEL: { id: 'BEL', name: 'بلجيكا',     flag: '🇧🇪', color: '#000000' },
  CRO: { id: 'CRO', name: 'كرواتيا',    flag: '🇭🇷', color: '#FF0000' },
  CAN: { id: 'CAN', name: 'كندا',        flag: '🇨🇦', color: '#FF0000' },
  SRB: { id: 'SRB', name: 'صربيا',      flag: '🇷🇸', color: '#C6363C' },
  SUI: { id: 'SUI', name: 'سويسرا',     flag: '🇨🇭', color: '#FF0000' },
  CMR: { id: 'CMR', name: 'الكاميرون',  flag: '🇨🇲', color: '#007A5E' },
  USA: { id: 'USA', name: 'الولايات المتحدة', flag: '🇺🇸', color: '#0A3161' },
  IRN: { id: 'IRN', name: 'إيران',       flag: '🇮🇷', color: '#239F40' },
  WAL: { id: 'WAL', name: 'ويلز',        flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', color: '#C8102E' },
  MEX: { id: 'MEX', name: 'المكسيك',    flag: '🇲🇽', color: '#006847' },
  SAU: { id: 'SAU', name: 'السعودية',   flag: '🇸🇦', color: '#006C35' },
  POL: { id: 'POL', name: 'بولندا',     flag: '🇵🇱', color: '#DC143C' },
  DEN: { id: 'DEN', name: 'الدنمارك',   flag: '🇩🇰', color: '#C60C30' },
  TUN: { id: 'TUN', name: 'تونس',        flag: '🇹🇳', color: '#E70013' },
  AUS: { id: 'AUS', name: 'أستراليا',   flag: '🇦🇺', color: '#00843D' },
  JPN: { id: 'JPN', name: 'اليابان',    flag: '🇯🇵', color: '#BC002D' },
  KOR: { id: 'KOR', name: 'كوريا الجنوبية', flag: '🇰🇷', color: '#003478' },
  GHA: { id: 'GHA', name: 'غانا',        flag: '🇬🇭', color: '#006B3F' },
  URU: { id: 'URU', name: 'أوروغواي',   flag: '🇺🇾', color: '#75AADB' },
  QAT: { id: 'QAT', name: 'قطر',         flag: '🇶🇦', color: '#8D1B3D' },
  ECU: { id: 'ECU', name: 'الإكوادور',  flag: '🇪🇨', color: '#FFD100' },
  SEN: { id: 'SEN', name: 'السنغال',    flag: '🇸🇳', color: '#00853F' },
  ITA: { id: 'ITA', name: 'إيطاليا',   flag: '🇮🇹', color: '#003399' },
}

// ─── WC 2026 Groups ───────────────────────────────────────────────────────────

export const GROUPS = [
  {
    id: 'A',
    name: 'المجموعة A',
    teams: [
      { team: TEAMS.ARG, played: 1, won: 1, draw: 0, lost: 0, gf: 2, ga: 0, pts: 3 },
      { team: TEAMS.POL, played: 1, won: 0, draw: 1, lost: 0, gf: 1, ga: 1, pts: 1 },
      { team: TEAMS.MEX, played: 1, won: 0, draw: 1, lost: 0, gf: 1, ga: 1, pts: 1 },
      { team: TEAMS.SAU, played: 1, won: 0, draw: 0, lost: 1, gf: 0, ga: 2, pts: 0 },
    ],
  },
  {
    id: 'B',
    name: 'المجموعة B',
    teams: [
      { team: TEAMS.FRA, played: 1, won: 1, draw: 0, lost: 0, gf: 4, ga: 1, pts: 3 },
      { team: TEAMS.DEN, played: 1, won: 0, draw: 1, lost: 0, gf: 0, ga: 0, pts: 1 },
      { team: TEAMS.TUN, played: 1, won: 0, draw: 1, lost: 0, gf: 0, ga: 0, pts: 1 },
      { team: TEAMS.AUS, played: 1, won: 0, draw: 0, lost: 1, gf: 1, ga: 4, pts: 0 },
    ],
  },
  {
    id: 'C',
    name: 'المجموعة C',
    teams: [
      { team: TEAMS.BRA, played: 1, won: 1, draw: 0, lost: 0, gf: 2, ga: 0, pts: 3 },
      { team: TEAMS.SRB, played: 1, won: 0, draw: 1, lost: 0, gf: 3, ga: 3, pts: 1 },
      { team: TEAMS.SUI, played: 1, won: 0, draw: 1, lost: 0, gf: 3, ga: 3, pts: 1 },
      { team: TEAMS.CMR, played: 1, won: 0, draw: 0, lost: 1, gf: 0, ga: 2, pts: 0 },
    ],
  },
  {
    id: 'D',
    name: 'المجموعة D',
    teams: [
      { team: TEAMS.ESP, played: 1, won: 1, draw: 0, lost: 0, gf: 7, ga: 0, pts: 3 },
      { team: TEAMS.GER, played: 1, won: 1, draw: 0, lost: 0, gf: 2, ga: 1, pts: 3 },
      { team: TEAMS.JPN, played: 1, won: 0, draw: 0, lost: 1, gf: 1, ga: 2, pts: 0 },
      { team: TEAMS.QAT, played: 1, won: 0, draw: 0, lost: 1, gf: 0, ga: 7, pts: 0 },
    ],
  },
  {
    id: 'E',
    name: 'المجموعة E',
    teams: [
      { team: TEAMS.ENG, played: 1, won: 1, draw: 0, lost: 0, gf: 6, ga: 2, pts: 3 },
      { team: TEAMS.USA, played: 1, won: 0, draw: 1, lost: 0, gf: 0, ga: 0, pts: 1 },
      { team: TEAMS.IRN, played: 1, won: 0, draw: 1, lost: 0, gf: 0, ga: 0, pts: 1 },
      { team: TEAMS.WAL, played: 1, won: 0, draw: 0, lost: 1, gf: 2, ga: 6, pts: 0 },
    ],
  },
  {
    id: 'F',
    name: 'المجموعة F',
    teams: [
      { team: TEAMS.MAR, played: 1, won: 1, draw: 0, lost: 0, gf: 2, ga: 1, pts: 3 },
      { team: TEAMS.BEL, played: 1, won: 0, draw: 1, lost: 0, gf: 1, ga: 1, pts: 1 },
      { team: TEAMS.CRO, played: 1, won: 0, draw: 1, lost: 0, gf: 1, ga: 1, pts: 1 },
      { team: TEAMS.CAN, played: 1, won: 0, draw: 0, lost: 1, gf: 1, ga: 2, pts: 0 },
    ],
  },
  {
    id: 'G',
    name: 'المجموعة G',
    teams: [
      { team: TEAMS.POR, played: 1, won: 1, draw: 0, lost: 0, gf: 3, ga: 2, pts: 3 },
      { team: TEAMS.URU, played: 1, won: 1, draw: 0, lost: 0, gf: 2, ga: 0, pts: 3 },
      { team: TEAMS.KOR, played: 1, won: 0, draw: 0, lost: 1, gf: 2, ga: 3, pts: 0 },
      { team: TEAMS.GHA, played: 1, won: 0, draw: 0, lost: 1, gf: 0, ga: 2, pts: 0 },
    ],
  },
  {
    id: 'H',
    name: 'المجموعة H',
    teams: [
      { team: TEAMS.NED, played: 1, won: 1, draw: 0, lost: 0, gf: 2, ga: 0, pts: 3 },
      { team: TEAMS.SEN, played: 1, won: 0, draw: 1, lost: 0, gf: 0, ga: 0, pts: 1 },
      { team: TEAMS.ECU, played: 1, won: 0, draw: 1, lost: 0, gf: 0, ga: 0, pts: 1 },
      { team: TEAMS.QAT, played: 1, won: 0, draw: 0, lost: 1, gf: 0, ga: 2, pts: 0 },
    ],
  },
]

// ─── Mock Matches ─────────────────────────────────────────────────────────────

export const MOCK_MATCHES = [
  {
    id: 'm1',
    status: 'LIVE',
    minute: '67',
    homeTeam: TEAMS.BRA,
    awayTeam: TEAMS.SRB,
    homeScore: 2,
    awayScore: 1,
    group: 'المجموعة C',
    venue: 'SoFi Stadium',
    city: 'لوس أنجلوس',
    stadium: { name: 'SoFi Stadium', city: 'لوس أنجلوس', capacity: 70240, info: 'أكبر ملعب مكشوف في الولايات المتحدة' },
    referee: 'Szymon Marciniak',
    startTime: '2026-06-15T19:00:00Z',
    events: [
      { minute: '23', type: 'goal',        team: 'BRA', player: 'فينيسيوس جونيور', assist: 'رودريغو' },
      { minute: '35', type: 'yellow_card', team: 'SRB', player: 'ميلينكوفيتش-سافيتش', assist: null },
      { minute: '55', type: 'goal',        team: 'BRA', player: 'رودريغو',           assist: 'فينيسيوس' },
      { minute: '61', type: 'goal',        team: 'SRB', player: 'ميتروفيتش',         assist: 'تاديتش' },
      { minute: '63', type: 'subst',       team: 'BRA', player: 'لوكاس باكيتا ← إندريك', assist: null },
    ],
    stats: {
      possession: [58, 42],
      shots: [14, 7],
      shotsOnTarget: [6, 3],
      corners: [5, 2],
      fouls: [9, 13],
    },
    lineups: {
      home: ['أليسون', 'دانيلو', 'ميليتاو', 'ماركينيوس', 'غابريل ماغالهايس', 'كاسيميرو', 'لوكاس باكيتا', 'رافينيا', 'رودريغو', 'فينيسيوس', 'إندريك'],
      away: ['فانياك', 'إيفانوفيتش', 'ميلينكوفيتش', 'بابيتش', 'لازوفيتش', 'لوكيتش', 'تاديتش', 'ميليفوييفيتش', 'كوستيتش', 'فلاهوفيتش', 'ميتروفيتش'],
    },
  },
  {
    id: 'm2',
    status: 'UPCOMING',
    minute: null,
    homeTeam: TEAMS.ARG,
    awayTeam: TEAMS.FRA,
    homeScore: null,
    awayScore: null,
    group: 'المجموعة A',
    venue: 'MetLife Stadium',
    city: 'نيوجيرسي',
    stadium: { name: 'MetLife Stadium', city: 'نيوجيرسي', capacity: 82500, info: 'يستضيف نهائي كأس العالم 2026' },
    referee: 'Daniele Orsato',
    startTime: '2026-06-15T21:00:00Z',
    events: [],
    stats: null,
    lineups: { home: [], away: [] },
  },
  {
    id: 'm3',
    status: 'UPCOMING',
    minute: null,
    homeTeam: TEAMS.ESP,
    awayTeam: TEAMS.GER,
    homeScore: null,
    awayScore: null,
    group: 'المجموعة D',
    venue: 'Allegiant Stadium',
    city: 'لاس فيغاس',
    stadium: { name: 'Allegiant Stadium', city: 'لاس فيغاس', capacity: 65000, info: 'الملعب المسقوف الوحيد في البطولة' },
    referee: 'Anthony Taylor',
    startTime: '2026-06-15T23:00:00Z',
    events: [],
    stats: null,
    lineups: { home: [], away: [] },
  },
  {
    id: 'm4',
    status: 'FINISHED',
    minute: '90',
    homeTeam: TEAMS.MAR,
    awayTeam: TEAMS.BEL,
    homeScore: 2,
    awayScore: 1,
    group: 'المجموعة F',
    venue: 'AT&T Stadium',
    city: 'دالاس',
    stadium: { name: 'AT&T Stadium', city: 'دالاس', capacity: 80000, info: 'أحد أكبر الملاعب المسقوفة في العالم' },
    referee: 'Clement Turpin',
    startTime: '2026-06-15T14:00:00Z',
    events: [
      { minute: '12', type: 'goal',        team: 'MAR', player: 'حكيم زياش',    assist: 'أمين حارث' },
      { minute: '42', type: 'goal',        team: 'BEL', player: 'روميلو لوكاكو', assist: 'كيفان دي برويني' },
      { minute: '78', type: 'goal',        team: 'MAR', player: 'يوسف النصيري',  assist: 'حكيم زياش' },
      { minute: '85', type: 'red_card',    team: 'BEL', player: 'ويتسيل',         assist: null },
    ],
    stats: {
      possession: [44, 56],
      shots: [9, 18],
      shotsOnTarget: [4, 5],
      corners: [3, 8],
      fouls: [14, 11],
    },
    lineups: { home: [], away: [] },
  },
  {
    id: 'm5',
    status: 'UPCOMING',
    minute: null,
    homeTeam: TEAMS.ENG,
    awayTeam: TEAMS.USA,
    homeScore: null,
    awayScore: null,
    group: 'المجموعة E',
    venue: 'Rose Bowl',
    city: 'باسادينا',
    stadium: { name: 'Rose Bowl', city: 'باسادينا', capacity: 88565, info: 'استضاف نهائي كأس العالم 1994' },
    referee: 'Felix Brych',
    startTime: '2026-06-16T02:00:00Z',
    events: [],
    stats: null,
    lineups: { home: [], away: [] },
  },
]

// ─── Mock Leaderboard ─────────────────────────────────────────────────────────

export const LEADERBOARD = [
  { rank: 1,  name: 'أحمد الشمري',  avatar: null, points: 145, correct: 18, streak: 4 },
  { rank: 2,  name: 'محمد الزهراني', avatar: null, points: 132, correct: 16, streak: 2 },
  { rank: 3,  name: 'سارة القحطاني', avatar: null, points: 120, correct: 15, streak: 3 },
  { rank: 4,  name: 'خالد العمري',   avatar: null, points: 108, correct: 13, streak: 0 },
  { rank: 5,  name: 'نورة الرشيد',   avatar: null, points: 95,  correct: 12, streak: 1 },
  { rank: 6,  name: 'عمر السعيد',    avatar: null, points: 87,  correct: 11, streak: 2 },
  { rank: 7,  name: 'لمياء العتيبي', avatar: null, points: 80,  correct: 10, streak: 0 },
  { rank: 8,  name: 'أنت',           avatar: null, points: 72,  correct: 9,  streak: 1, isMe: true },
  { rank: 9,  name: 'فيصل الدوسري',  avatar: null, points: 65,  correct: 8,  streak: 0 },
  { rank: 10, name: 'ريم الحربي',    avatar: null, points: 58,  correct: 7,  streak: 0 },
]

// ─── Mock Players (card system) ───────────────────────────────────────────────

export const PLAYER_RARITIES = {
  COMMON:    { label: 'عادي',    color: '#6B7280', bg: '#1F2937' },
  RARE:      { label: 'نادر',    color: '#3B82F6', bg: '#1E3A5F' },
  LEGENDARY: { label: 'أسطوري', color: '#F59E0B', bg: '#3D2A00' },
}

export const MOCK_PLAYERS = [
  {
    id: 'p1',
    name: 'ليونيل ميسي',
    team: TEAMS.ARG,
    position: 'مهاجم',
    number: 10,
    rarity: 'LEGENDARY',
    power: 96,
    wcGoals: 13,
    age: 38,
    club: 'إنتر ميامي',
    stats: { goals: 13, assists: 8, matches: 26 },
    injured: false,
  },
  {
    id: 'p2',
    name: 'كيليان مبابي',
    team: TEAMS.FRA,
    position: 'مهاجم',
    number: 10,
    rarity: 'LEGENDARY',
    power: 95,
    wcGoals: 12,
    age: 27,
    club: 'ريال مدريد',
    stats: { goals: 12, assists: 6, matches: 22 },
    injured: false,
  },
  {
    id: 'p3',
    name: 'فينيسيوس جونيور',
    team: TEAMS.BRA,
    position: 'جناح',
    number: 7,
    rarity: 'RARE',
    power: 92,
    wcGoals: 5,
    age: 25,
    club: 'ريال مدريد',
    stats: { goals: 5, assists: 7, matches: 14 },
    injured: false,
  },
  {
    id: 'p4',
    name: 'إيرلينغ هالاند',
    team: TEAMS.NED,
    position: 'مهاجم',
    number: 9,
    rarity: 'LEGENDARY',
    power: 93,
    wcGoals: 4,
    age: 25,
    club: 'مانشستر سيتي',
    stats: { goals: 4, assists: 2, matches: 8 },
    injured: false,
  },
  {
    id: 'p5',
    name: 'حكيم زياش',
    team: TEAMS.MAR,
    position: 'جناح',
    number: 7,
    rarity: 'RARE',
    power: 85,
    wcGoals: 3,
    age: 31,
    club: 'غلطة سراي',
    stats: { goals: 3, assists: 5, matches: 12 },
    injured: false,
  },
  {
    id: 'p6',
    name: 'لوكاس باكيتا',
    team: TEAMS.BRA,
    position: 'وسط',
    number: 8,
    rarity: 'RARE',
    power: 88,
    wcGoals: 1,
    age: 26,
    club: 'وست هام',
    stats: { goals: 1, assists: 4, matches: 12 },
    injured: false,
  },
]

// ─── Mock Friend Groups ────────────────────────────────────────────────────────

export const MOCK_FRIEND_GROUPS = [
  {
    id: 'fg1',
    name: 'أصدقاء العمل',
    code: 'KRX-7842',
    admin: 'أنت',
    members: [
      { name: 'أنت',           points: 72, rank: 1, isMe: true },
      { name: 'فهد الغامدي',   points: 65, rank: 2 },
      { name: 'نواف الرشيدي',  points: 58, rank: 3 },
      { name: 'رانيا السهلي',  points: 40, rank: 4 },
    ],
  },
  {
    id: 'fg2',
    name: 'العائلة',
    code: 'KRX-3391',
    admin: 'أبي',
    members: [
      { name: 'أخي الكبير',   points: 90, rank: 1 },
      { name: 'أنت',           points: 72, rank: 2, isMe: true },
      { name: 'أبي',           points: 60, rank: 3 },
    ],
  },
]
